### ISSUE TITLE
Tapping on input form in output pane differs from mobile Replete

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-macos#39]
If you tap on an input form in the output pane, it is automatically copied into the input pane.

This seems like cool behavior. Maybe we can sort out something to make things consistent across all the Replete's for this case. (Either make it behave like mobile Replete, or consider revising mobile Replete if appropriate.)

**Comment by wildthink** [comment]
Its easy to make it an option as well. One (hidden) difference is the output is a single textView and its also selectable and copyable.

**Comment by mfikes** [comment]
One issue I encountered is if you want to select from the output pane, it is relatively easy to accidentally click somewhere and have that copied to the input pane (effectively deleting what you were typing in the input pane).

Given this, maybe an improvement would be to simply just let people select anywhere from the output pane. (In other words, stick with a very simply select-and-copy model, and avoid inherent behavior related to the fact that the app actually knows that portions of the output pane are history items.)

**Comment by wildthink** [comment]
Yeah, I can see how that’s an issue. I can fix that.

May be nice to have a “button” in the side ruler area to select to whole expression. Next version perhaps.

Jason

**Comment by mfikes** [comment]
Yeah, in this case, maybe simpler is better for now. Additionally, if the "click-and-copy" behavior is eliminated, this would also fix a related issue where the format of the copied text is copied into the input pane (which ends up making things look a bit odd).
